### PR TITLE
Add xUnit Tests, WeightedGraph, modified existing Graph and MapHashedLinked

### PR DESCRIPTION
**Pull request by AzuxirenLeadGuy**
# **New/Added code**

## xUnit Test cases
Modified the `Towel/Examples/DataStructures/DataStructures.csproj` to support xUnit test cases. The original program can run, and now it contains xUnit test cases as well for a few Data Structures. 

## IWeightedGraph<V, W>
A basic interface for a weighted graph, given as follows:

```cs

	public interface IWeightedGraph<V, W> : IGraph<V> where W : notnull, IComparable<W>
	{
		void IGraph<V>.Add(V start, V end) => Add(start, end, default(W));

		void Add(V start, V end, W weight);

		bool Adjacent(V a, V b, out W weight);
	}
```

## WeightedGraph<V, W>
Implementation of the weighted graph

# Modifed Code

## GraphMap<T>

Removed bugs (`_edges` not being updated on add/removal of edges), implemented methods that threw `NotImplementedException`. Now all xUnit Test case are passing.

## IMap<T, K>

Added method `IEnumerable<(K Key, T Value)> GetEnumeratorPairs {get;}`
This allows iterating through the Map in terms of pairs of (Key, Value) tuple, similar to how Dictionary<T, K> does.

## MapHashLinked<T, K>

Implemented `GetEnumeratorPairs` property for `MapHashLinked`

# Issues

## GraphSetOmnitree<T>

The `Adjacent(T a, T b)` method is failing the test. Tried to work on it to no avail.

### CODE REVIEW

**Comment by ZacharyPatten** [comment]
Thanks for the interest in contributing. :)

I will review the PR as soon as I can. One thing I already notice though is the `where W : notnull, IComparable<W>` constraints. Those aren't how comparisons are usually handled in Towel. Rather than using interfacing, I let the user pass in a comparison struct or delegate to provide the comparison function rather than interfacing, because:

1. struct generic parameters are faster than interfacing (virtual method look ups)
2. passing in the comparison function allows the user to customize the comparison without creating a second type

If the user doesn't pass in a comparison struct/delegate then it will default to the "Statics.Compare<T>" method, which has the overhead of a delegate invocation, but has the smallest code footprint from the user's side.

**Comment by ZacharyPatten** [comment]
I made quite a few changes:
1. There is already a testing project in the "Tools" folder called "Towel_Testing". I moved the unit tests in there rather than the "Examples" folder. Also, I'm currently using MSTest rather than XUnit, so I converted the tests where appropriate, but the logic of the tests should be the same.
2. I think I had a bug in the Omnitree where I had `!InclusionCheck(child.Bounds, bounds)` when it needed to be `InclusionCheck(child.Bounds, bounds)` (removed the `!`).
3. I made a few minor changes to the code to match the style currently used in Towel, such as removing the "Add" method because there is an extension method for it.

I need more time to review the code though. I think there are still a number of changes I would like to make before pulling it in.

Feel free to provide feedback on the adjustments I have made so far.

**Comment by AzuxirenLeadGuy** [comment]
>  There is already a testing project in the "Tools" folder called "Towel_Testing".

Oh, sorry I missed it. I usually expect the Testing folder to begin at the root folder; and assumed there weren't any tests in the repository.

The rest seems okay.

**Comment by AzuxirenLeadGuy** [comment]
Sorry... Closed by mistake

**Comment by ZacharyPatten** [comment]
Notes on some more changes I made:

1. Change name from `GraphWeighted` to `GraphUndirectedWeightedMap` to be more specific. The interface was also renamed. _The other graphs in Towel are currently directed rather than undirected, so I need some way to distinguish._
2. optimized the `NodeCount` property
3. cached the edge count to optimized the `EdgeCount` property
4. Updated the Stepper/Keys methods to allow struct generic parameters as the base implementation rather than delegates. This is an optimization should the user want to go to the effort. I think there is a way to implement this via extension methods but I haven't attempted it just yet, because I need to re-write the omnitree first.

I will eventually want a base version of this data structure that uses struct generic parameters for the Hashing and Equality delegates (rather than falling back to the `Statics.Hash` and `Statics.Equate` methods). But that can come in the future; I won't prevent the PR from being merged until that is done.

> Although I may merge this PR sooner than later, I just want to let you know that I have some plans that involve a redesign of some of the data structure code in the future. If you want more info I can elaborate, but I'm considering killing all non-struct generic data structure implementations in favor of static factory methods to aid with construction. I also need to redesign several the interfaces. And... if "duck-typing" is ever added to C# that will also completely change how I implement data structures that are implemented with other data structures.

**Comment by ZacharyPatten** [comment]
including the ".vscode" folder in the repo is intentional. I have included the files necessary for people to open Towel and run the examples in VSC

**Comment by AzuxirenLeadGuy** [comment]
> Change name from GraphWeighted to GraphUndirectedWeightedMap to be more specific. The interface was also renamed.

That is not true. The weighted graph I implemented is Directed. You can confirm it by this test code below which is passing

```cs
	[TestMethod]
	public void DirectedTest()
	{
		GraphUndirectedWeightedMap<int, float> graph = new();
		graph.Add(1);
		graph.Add(2);
		graph.Add(1,2,1.1f);
		Assert.IsFalse(graph.Adjacent(2,1)); 
               //Test has passed. Adding Edge (1 -> 2) does not also add Edge (2 -> 1)
	}
```
I believe the confusion may be due to the fact I'm storing the Incoming Edges and Outgoing Nodes in the `MapHashLinked<V, W> Structure`. The only reason for this is to properly remove all the edges of the node. The `Remove(Node n)` method removes all edges (incoming and outgoing) related to the node and then proceeds to remove the said node from the structure.

So the implemented weighted graph is directed, and not undirected.

Also, I don't see much point in making an undirected graph, since it can be implemented simply by the program to Add edge `b->a` for every `a->b` edge queried to add

**Comment by AzuxirenLeadGuy** [comment]
> including the ".vscode" folder in the repo is intentional. I have included the files necessary for people to open Towel and run the examples in VSC

I understand. I added `.vscode` folder to be ignored because VS code also creates a `setting.json` file in the said folder where it stores the customized settings of the user. This file should not be included in git repository. 

Anyway, opening the folder as a workspace is a good enough workaround for me.

**Comment by AzuxirenLeadGuy** [comment]
Also, regarding the undirected graph, we can add the following to the common graph interface

```cs
public interface IGraph<T>
{
    public bool IsDirected {get;}
}
```
This property is set on the initialization of the graph

Then for every graph that is implemented, it can add edges like

```cs
    void Add(Node a, Node b)
    {
        AddEdge(a, b);
        if(!IsDirected) AddEdge(b, a);
    }
```

Please provide feedback on this approach. I won't be able to work on it immediately, although it shouldn't require much effort.

**Comment by ZacharyPatten** [comment]
If it is a directed graph that is my bad. I will fix the name. That was a rather quick assumption without mich testing.

I like the idea of having an "IsDirected" on the graph interface, but hold off on changing the interfaces for a bit. I need to make some changes to the interfaces regarding the Stepper functions. However, there is a fundamental problem though in that you can't interface methods with generic parameters. I've been srruggling with this problem for a long time now, and I havent decided on a proper design to address it. Rather than the interfaces all having `Stepper(Action<T> action)` it really needs to be `Stepper<Step>(Step step = default) where Step : struct, IAction<T>`, but as mentioned that currently isn't possible as far as I'm aware. C# really needs duck typing because interfacing just isn't enough.

**Comment by AzuxirenLeadGuy** [comment]
Now I haven't fully gone through all the DSs in Towel; but to be honest, I don't think using this Step delegate is the best approach. I believe instead of "tunnelling" a method/delegate in a DS, it would be better just to expose the data itself. This is how Microsoft did it with `IEnumerable<T>` and `IEnumerator<T>`. The data is exposed with a `foreach` statement, and logic is written inside the loop; the action needn't be passed as a delegate (although you can).

But of course, I may be missing something since I haven't gone through the entire design of the framework. So can you please explain how this Step delegate approach is better than simply enumerating over the data?

**Comment by ZacharyPatten** [comment]
It is for optimal performance. Passing in the functionality (such as is done with my "Stepper" methods) is faster than passing back the values (such as is done with "IEnumerable). This is because when you use `struct` generic parameters they are reified by the JIT, which also has the ability to inline methods. The "Benchmark 2" example I have posted here https://github.com/dotnet/csharplang/discussions/2904 demonstrates the performance difference (specifically "GenericStructWhereAction" is the fastest benchmark). However, `IEnumerable<T>` generally results in cleaner code since it has built in syntax in the laguage (`yield return` and `foreach`).

So... my current mentality is to support both patterns and let the user decide which one they need for their use case (performance or clean code).

**Comment by AzuxirenLeadGuy** [comment]
> So... my current mentality is to support both patterns and let the user decide which one they need for their use case (performance or clean code).

Alright. That makes sense.

> I've been srruggling with this problem for a long time now, and I havent decided on a proper design to address it. Rather than the interfaces all having `Stepper(Action<T> action)` it really needs to be `Stepper<Step>(Step step = default) where Step : struct, IAction<T>`

If you don't mind, can you explain this bit?

**Comment by ZacharyPatten** [comment]
> > I've been srruggling with this problem for a long time now, and I havent decided on a proper design to address it. Rather than the interfaces all having Stepper(Action<T> action) it really needs to be Stepper<Step>(Step step = default) where Step : struct, IAction<T>
>
> If you don't mind, can you explain this bit?

Sure. :)

The following code example uses Benchmarkdotnet and should compile in .NET 5:

```cs
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Attributes;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections;

using ConsoleApp2.B;
using ConsoleApp2.C;

namespace ConsoleApp2
{
	class Program
	{
		public static void Main()
		{
			BenchmarkRunner.Run<Benchmarks>();
		}
	}

	public class Benchmarks
	{
		[Params(1, 10, 100, 1000, 10000, 100000)]
		public int N;

		A.IDataStructure<int> a;
		B.IDataStructure<int> b;
		C.IDataStructure<int> c;

		[IterationSetup]
		public void IterationSetup()
		{
			int[] values = Enumerable.Range(0, N).ToArray();
			a = new A.SomeDataStructure<int>() { values = values.ToArray() };
			b = new B.SomeDataStructure<int>() { values = values.ToArray() };
			c = new C.SomeDataStructure<int>() { values = values.ToArray() };
		}

		[Benchmark]
		public void A()
		{
			int sum = 0;
			foreach (int value in a)
			{
				sum += value;
			}
		}

		[Benchmark]
		public void B()
		{
			int sum = 0;
			b.Stepper(x => { sum += x; });
		}

		[Benchmark]
		public void C1()
		{
			SumStatic sum = default;
			c.Stepper<int, SumStatic>(sum);
		}

		struct SumStatic : IAction<int>
		{
			public static int sum;

			public void Do(int arg1)
			{
				sum += arg1;
			}
		}

		[Benchmark]
		public void C2()
		{
			Ref<int> sumValue = new();
			SumNonStatic sum = new(sumValue);
			c.Stepper<int, SumNonStatic>(sum);
		}

		struct SumNonStatic : IAction<int>
		{
			public Ref<int> sum;

			public SumNonStatic(Ref<int> value) => sum = value;

			public void Do(int arg1)
			{
				sum.value += arg1;
			}
		}

		class Ref<T>
		{
			public T value;
		}

		[Benchmark]
		public void C3()
		{
			int sum = 0;
			c.Stepper(x => { sum += x; });
			Console.WriteLine($"BLAH BLAH N{N} sum{sum}");
		}
	}

	namespace A
	{
		interface IDataStructure<T> : IEnumerable<T> { }

		class SomeDataStructure<T> : IDataStructure<T>
		{
			internal T[] values;

			public IEnumerator<T> GetEnumerator()
			{
				foreach (T value in values)
				{
					yield return value;
				}
			}

			IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
		}
	}

	namespace B
	{
		interface IDataStructure<T>
		{
			bool Stepper(Func<T, bool> func);
		}

		class SomeDataStructure<T> : IDataStructure<T>
		{
			internal T[] values;

			public bool Stepper(Func<T, bool> func)
			{
				foreach (T value in values)
				{
					if (func(value))
					{
						return true;
					}
				}
				return false;
			}
		}

		static class Extensions
		{
			public static void Stepper<T>(this IDataStructure<T> dataStructure, Action<T> action)
			{
				dataStructure.Stepper(x => { action(x); return false; });
			}
		}
	}

	namespace C
	{
		public interface IAction<T1>
		{
			void Do(T1 arg1);
		}

		public interface IFunc<T1, TResult>
		{
			TResult Do(T1 arg1);
		}

		interface IDataStructure<T>
		{
			bool Stepper<Step>(Step step)
				where Step : struct, IFunc<T, bool>;
		}

		class SomeDataStructure<T> : IDataStructure<T>
		{
			internal T[] values;

			public bool Stepper<Step>(Step step = default)
				where Step : struct, IFunc<T, bool>
			{
				foreach (T value in values)
				{
					if (step.Do(value))
					{
						return true;
					}
				}
				return false;
			}
		}

		static class Extensions
		{
			public static void Stepper<T, Step>(this IDataStructure<T> dataStructure, Step step)
				where Step : struct, IAction<T>
			{
				StepBreakFromAction<T, Step> breakableStep = new() { StepFunction = step };
				dataStructure.Stepper<StepBreakFromAction<T, Step>>(breakableStep);
			}

			public struct StepBreakFromAction<T, Step> : IFunc<T, bool>
				where Step : struct, IAction<T>
			{
				internal Step StepFunction;
				public bool Do(T value) { StepFunction.Do(value); return false; }
			}

			public static void Stepper<T>(this IDataStructure<T> dataStructure, Action<T> step)
			{
				StepBreakFromAction<T, ActionRuntime<T>> breakableStep = new() { StepFunction = step };
				dataStructure.Stepper<StepBreakFromAction<T, ActionRuntime<T>>>(breakableStep);
			}

			public struct ActionRuntime<T1> : IAction<T1>
			{
				/// <summary>The delegate instance.</summary>
				internal Action<T1> _delegate;
				/// <summary>Invocation of the delegate.</summary>
				public void Do(T1 arg1) => _delegate(arg1);
				/// <summary>Implicit caster from a delegate.</summary>
				public static implicit operator ActionRuntime<T1>(Action<T1> @delegate) => new() { _delegate = @delegate, };
			}
		}
	}
}

```
- The **A** benchmarks are just a control that uses `IEnumerable<T>` with a `foreach` loop.
- The **B** benchmarks are what the current interfaces in Towel look like regarding the stepper methods. The methods on the `IDataStructure` interface use the delegate types in the BCL like `Action` and `Func`. See <https://github.com/ZacharyPatten/Towel/blob/8c1822b9271e586843bebaa5ca14e34fd5c15af3/Sources/Towel/DataStructures/DataStructure.cs#L17>
- The **C** benchmarks _don't use the delegate types from the BCL like B does._ Instead, the C benchmarks use struct generic parameters as an alternative to delegates. **C1** and **C2** are essentially the same just one uses a static `int` and one uses a referenced one. However, the C approach can still support delegates like the B approach if you want to as demonstrated in benchmark **C3**.

I have run that benchmark on my computer and the **C** benchmarks run the fastest. So for me, the takeaway is that I need to convert the data structure interfaces in Towel from style B to style C, but that is a farily big task.

Hopefully that makes sense. I would be happy to elaborate more with a demonstration if desired.

> Some Extra notes:
> - I dont want to have to make a ton of identical structs wrappers for varying dinemsions of data... so i probably need to start using tuples
> - I already need to rewrite the Omnitee, so I kinda need to finish that first before changing the interfaces
> - although the **C** examples from above are the fastest and they can fully support the **B** examppes too, I still whish there was a better way to do it in C# (better syntax). because the code is rather verbose/ugly

**Comment by ZacharyPatten** [comment]
changes to the new code
- reverted the name back to `IGraphWeighted<V, W>` and `GraphWeightedMap<V, W>`
- renamed `GetEnumeratorPairs` to `GetPairs` and flipped the types of the tuple from `(K, T)` to `(T, K)`
    - I realize most people are used to "K, T" rather than "T, K" but I may implement similar methods in other data structures and I want it to remain as consistent as possible. for example the Omnitree may have "T, A1, A2, A3". So I want the first type of the tuple to be the value of the data structure.
- I implemented the struct generic implementations of the edges stepper methods on the `GraphWeightedMap<V, W>` type

changes to the existing code in Towel
- renamed `Map` breakable `Keys` method to `KeysBreak`
- renamed `Map` pair `Stepper` methods to `Pairs` method to `PairsBreak`
- renamed `Graph` edge `Stepper` methods to `Edges` and `EdgeBreak`

There are probably a few other changes I didn't include in this list...

Towel is still in an "alpha" phase on the whole, so we don't need to get the code perfectly clean, fully featured, or fully unit tested to merge the PR into master. Improvements and unit tests can be handled in future updates/PRs. What is your current opinion of the state of the PR? Do you see anything you want to address before the PR is merged?

**Comment by ZacharyPatten** [comment]
Also, in regards to the `.vscode/settings.json` file, the reason I currently included it was to help with people who are not as familiar with C# with some default settings. I still see a lot of C# developers in VSC that don't even know about the `"csharp.semanticHighlighting.enabled": true,` setting. However, for experienced developers, I understand that including it in the repo is annoying. Feel free to open an issue for that topic in the repo and we can discuss the topic there.

**Comment by AzuxirenLeadGuy** [comment]
Thank you for your detailed explanation.

I've been thinking of a better approach similar to your implementation of C.

I came up with the following approach given under `namespace D`. My approach here is to use the custom `IActPerformer<T>` as a return type in `StepAction()` method.

I implemented as follows.
```cs
namespace D
    {
        public interface IActPerformer<T>
        {
            bool ActPerform(T t);
        }
        public interface IDataStructure<T> : IEnumerable<T>
        {
            A StepAction<A>() where A : struct, IActPerformer<T>;
        }
        public struct SomeDataStructure<T> : IDataStructure<T>
        {
            public T[] values;
            public IEnumerator<T> GetEnumerator() { foreach (var i in values) yield return i; }
            public A StepAction<A>() where A : struct, IActPerformer<T>
            {
                A a = default;
		if(values!=null && values.Length > 0)
		{
			for (int i = 0, l = values.Length; (i < l) && a.ActPerform(values[i]); i++) ;
		}
                return a;
            }

            IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
        }
        public struct MyStaticActionPerformer : IActPerformer<int>
        {
            public static int sum;
            public bool ActPerform(int t)
            {
                sum += t;
                return true;
            }
        }
        public struct MyNonStaticActionPerformer : IActPerformer<int>
        {
            public int sum;
            public bool ActPerform(int t)
            {
                sum += t;
                return true;
            }
        }
    }
```

and benchmarked it by adding this to your code
```cs
        D.IDataStructure<int> d;
        ...
            d = new D.SomeDataStructure<int>() { values = values.ToArray() };
        ...
        [Benchmark]
        public void D1()
        {
            d.StepAction<D.MyStaticActionPerformer>();
        }
        [Benchmark]
        public void D2()
        {
            d.StepAction<D.MyNonStaticActionPerformer>();
        }
```

I obtained the following benchmarks:
```

| Method |      N |          Mean |       Error |       StdDev |          Median |          P95 |
|------- |------- |--------------:|------------:|-------------:|----------------:|-------------:|
|      A |      1 |   1,092.78 ns |   325.19 ns |    948.59 ns |     977.5000 ns |   2,874.0 ns |
|      B |      1 |   1,537.80 ns |   398.10 ns |  1,154.95 ns |   1,048.0000 ns |   3,855.0 ns |
|     C1 |      1 |     236.89 ns |   115.50 ns |    329.54 ns |      69.0000 ns |     978.0 ns |
|     C2 |      1 |   1,050.62 ns |   342.35 ns |    942.93 ns |     978.0000 ns |   2,740.8 ns |
|     C3 |      1 |   1,263.93 ns |   431.39 ns |  1,271.97 ns |     733.5000 ns |   3,844.5 ns |
|     D1 |      1 |     254.65 ns |   110.06 ns |    319.32 ns |      35.5000 ns |     942.7 ns |
|     D2 |      1 |     486.99 ns |   188.43 ns |    555.59 ns |     453.5000 ns |   1,501.5 ns |
|      A |     10 |   1,226.25 ns |   357.15 ns |  1,018.96 ns |     978.5000 ns |   3,548.1 ns |
|      B |     10 |   1,254.15 ns |   319.45 ns |    921.67 ns |   1,047.0000 ns |   2,951.0 ns |
|     C1 |     10 |     304.11 ns |   166.17 ns |    489.95 ns |       0.0000 ns |   1,328.0 ns |
|     C2 |     10 |   1,013.75 ns |   278.98 ns |    786.87 ns |     768.0000 ns |   2,584.4 ns |
|     C3 |     10 |   1,236.59 ns |   332.45 ns |    959.18 ns |   1,012.5000 ns |   2,881.5 ns |
|     D1 |     10 |     539.90 ns |   243.54 ns |    706.54 ns |      70.0000 ns |   2,025.0 ns |
|     D2 |     10 |     229.21 ns |   127.93 ns |    375.19 ns |       0.0000 ns |     984.9 ns |
|      A |    100 |     889.00 ns |   196.76 ns |    554.97 ns |     909.0000 ns |   1,848.1 ns |
|      B |    100 |   1,740.43 ns |   200.53 ns |    565.59 ns |   1,676.5000 ns |   2,615.6 ns |
|     C1 |    100 |     480.08 ns |   189.58 ns |    558.98 ns |     454.0000 ns |   1,471.0 ns |
|     C2 |    100 |   1,559.51 ns |   382.30 ns |  1,084.53 ns |     977.0000 ns |   3,380.0 ns |
|     C3 |    100 |   1,669.34 ns |   298.13 ns |    864.92 ns |   1,397.5000 ns |   3,492.3 ns |
|     D1 |    100 |     750.44 ns |   235.89 ns |    691.82 ns |     489.0000 ns |   1,886.0 ns |
|     D2 |    100 |      49.44 ns |    45.18 ns |    125.94 ns |       0.0000 ns |     454.5 ns |
|      A |   1000 |   5,998.85 ns |   213.97 ns |    582.12 ns |   5,797.0000 ns |   7,194.0 ns |
|      B |   1000 |   6,537.40 ns |   354.35 ns |    951.93 ns |   6,320.5000 ns |   7,822.0 ns |
|     C1 |   1000 |   1,669.16 ns |   196.86 ns |    532.22 ns |   1,536.5000 ns |   2,794.7 ns |
|     C2 |   1000 |   1,823.09 ns |   437.38 ns |  1,275.85 ns |   1,468.0000 ns |   4,261.0 ns |
|     C3 |   1000 |   3,787.59 ns |   653.32 ns |  1,905.76 ns |   2,863.0000 ns |   7,255.8 ns |
|     D1 |   1000 |   1,792.38 ns |   195.07 ns |    533.99 ns |   1,955.0000 ns |   2,445.0 ns |
|     D2 |   1000 |     779.40 ns |   268.14 ns |    786.42 ns |     489.0000 ns |   1,962.9 ns |
|      A |  10000 |  53,860.38 ns | 1,087.67 ns |  1,488.81 ns |  53,149.0000 ns |  56,361.2 ns |
|      B |  10000 |  53,880.00 ns |   846.95 ns |  1,527.23 ns |  53,289.0000 ns |  56,851.0 ns |
|     C1 |  10000 |  17,623.57 ns |   240.65 ns |    225.10 ns |  17,739.5000 ns |  17,900.5 ns |
|     C2 |  10000 |   7,061.77 ns |   753.33 ns |  2,049.48 ns |   6,215.5000 ns |  11,784.8 ns |
|     C3 |  10000 |  20,510.30 ns |   414.61 ns |    704.04 ns |  20,393.0000 ns |  21,594.8 ns |
|     D1 |  10000 |  24,471.08 ns | 3,487.00 ns | 10,281.51 ns |  18,054.0000 ns |  42,323.6 ns |
|     D2 |  10000 |   5,399.02 ns |   391.36 ns |  1,024.12 ns |   5,238.5000 ns |   7,556.5 ns |
|      A | 100000 | 534,311.77 ns | 7,522.01 ns | 15,534.26 ns | 532,047.0000 ns | 560,996.2 ns |
|      B | 100000 | 540,253.57 ns | 7,080.48 ns |  6,276.66 ns | 541,231.5000 ns | 549,203.4 ns |
|     C1 | 100000 | 185,457.89 ns | 6,318.51 ns | 16,534.43 ns | 180,329.0000 ns | 223,640.4 ns |
|     C2 | 100000 |  59,733.00 ns | 4,809.39 ns | 12,753.81 ns |  54,615.5000 ns |  87,339.9 ns |
|     C3 | 100000 | 190,048.25 ns | 2,545.64 ns |  1,987.47 ns | 190,037.0000 ns | 192,690.5 ns |
|     D1 | 100000 | 183,235.07 ns | 3,654.00 ns |  7,627.27 ns | 180,818.5000 ns | 199,801.1 ns |
|     D2 | 100000 |  53,763.82 ns | 1,631.61 ns |  4,211.70 ns |  52,729.5000 ns |  60,778.7 ns |
```

Let me know what you think.

**Comment by AzuxirenLeadGuy** [comment]
> Also, in regards to the `.vscode/settings.json` file, the reason I currently included it was to help with people who are not as familiar with C# in VSC with some default settings. I still see a lot of C# developers in VSC that don't even know about the `"csharp.semanticHighlighting.enabled": true,` setting. However, for experienced developers, I understand that including it in the repo is annoying. Feel free to open an issue for that topic in the repo and we can discuss the topic there.
> 
> Maybe the annoyance of dealing with that file outweighs the potential benefit it has for helping new developers by applying some default settings.

As I said, I've figured a workaround so it doesn't bother me too much. I feel the correct approach would be to add the `.vscode` folder to the `.gitignore` and rename the current folder to `.vscode-default` folder, with instructions in the Readme.MD to copy the files.

**Comment by AzuxirenLeadGuy** [comment]
Completed the methods that were marked as "Not Implemented", and added Test cases to confirm that they are working

**Comment by AzuxirenLeadGuy** [comment]
> Towel is still in an "alpha" phase on the whole, so we don't need to get the code perfectly clean, fully featured, or fully unit tested to merge the PR into master. Improvements and unit tests can be handled in future updates/PRs. What is your current opinion of the state of the PR? Do you see anything you want to address before the PR is merged? 

This PR was for WeightedGraph, and I feel that the code for that is pretty much done. So as far as this PR is concerned, I think it is ready to be merged. The discussions we've had over the implementation of `IDataStructure` should be moved and worked elsewhere.

**Pull request merged**
