### PR TITLE
Use Memory<T> / Span<T>

### PR DESCRIPTION
**Pull request by HurricanKai**
#### Description
Update all Array usages to use Memory<T> / Span<T>

#### Purpose
Better compatability & Performance

#### Issues
#48 

#### Mentions
@ZacharyPatten

### CODE REVIEW

**Comment by HurricanKai** [comment]
@ZacharyPatten how do you think `IArray<T>`/`Array<T>` should be handled.
I tbh don't understand the purpose of those anyways, should I leave the API as is, and still replace them with `Memory<T>` under the hood, rename them, or just leave them be?

**Comment by HurricanKai** [comment]
@ZacharyPatten looking at some more of the advanced code, these abstractions over built-in features like `GetIndex`, `SetIndex`, `Array` etc. seem pointless to me, and are hurting performance a lot.

**Comment by ZacharyPatten** [comment]
`Span<T>` and `Memory<T>` are nice but they do not abstract things enough. Having wrappers around getters and setters allow you to abstract the data structure being used in an algorithm. For example, the sorting algorithms work on arrays and lists, but they can also work on dictionary or any other `int` indexed data structure. It will even work on data structures made in other people's libraries.

The runtime delegate versions (`GetIndex<T` and `SetIndex<T>`) are slow for sure, but they are only syntax sugar for people who want to use the delegate/lambda style syntax. The more optimized approach is to make a `struct` rather than use a delegate. Then there is no delegate at runtime and it will potentially be inlined by the JIT.

I elaborate on this topic here: https://github.com/dotnet/csharplang/issues/2904

Also, the benchmarking code for the sorting algorithms is another example of how structs > delegates/lambdas for `static` function references: https://github.com/ZacharyPatten/Towel/blob/master/.github/Pages/Benchmarks.md

**Comment by ZacharyPatten** [comment]
Also, I never actually thought about using `Memory<T>` underneath the data structures. I was referring to other areas of the code when I commented that I want to use them.

I'm not opposed to using `Memory<T>` underneath the data structures if it works, but now I'm curious about stuff like serialization. I don't see the `Serializable` attribute on `Memory<T>`, and I would assume (knowing what Memory is) that it is not serializable.

That isn't necessarily a deal breaker, it just means custom serializers are required. The data structures with delegates underneath them already require custom serialization practices anyway.

**Comment by HurricanKai** [comment]
> Span<T> and Memory<T> are nice but they do not abstract things enough
I don't understand what you mean?
Only downside is that Span/Memory are linear only. but I don't see a use case where that is a problem.

**Comment by HurricanKai** [comment]
Also, when I say these add overhead, I mean a lot of it
As an example, bubble sort.
Before <https://github.com/ZacharyPatten/Towel/blob/444eea7d0da4a8a78410cd48b506a2a65ec7b23f/Sources/Towel/Sort.cs#L82>
After:
```cs
public static void New<T, TCompare>(Span<T> span, TCompare compare)
    where TCompare : IComparer<T>
{
    for (int i = 0; i < span.Length; i++)
    {
        for (int j = 0; j < span.Length - 1; j++)
        {
            if (compare.Compare(span[j], span[j + 1]) is 1)
            {
                var temp = span[j + 1];
                span[j + 1] = span[j];
                span[j] = temp;
            }
        }
    }
}
```

Benchmark:
```ini
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.19569
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
.NET Core SDK=3.1.101
  [Host]     : .NET Core 3.1.1 (CoreCLR 4.700.19.60701, CoreFX 4.700.19.60801), X64 RyuJIT
  Job-KFRPCW : .NET Framework 4.8 (4.8.4084.0), X64 RyuJIT
  Job-IXSZEK : .NET CoreRT 1.0.28703.02 @BuiltBy: dlab14-DDVSOWINAGE101 @Branch: master @Commit: 65f1d8fb61c8d4d426562f8861a89bfd24b173b4, X64 AOT

InvocationCount=1  UnrollFactor=1
```

|  Method |    Runtime | Size |             Mean |           Error |          StdDev |           Median |
|-------- |----------- |----- |-----------------:|----------------:|----------------:|-----------------:|
| Current |   .NET 4.8 |    2 |         454.2 ns |        31.77 ns |        91.67 ns |         500.0 ns |
|     New |   .NET 4.8 |    2 |         173.4 ns |        24.20 ns |        69.06 ns |         200.0 ns |
| Current | CoreRt 3.1 |    2 |         232.3 ns |        31.60 ns |        91.18 ns |         200.0 ns |
|     New | CoreRt 3.1 |    2 |         207.3 ns |        37.72 ns |       108.82 ns |         200.0 ns |
| Current |   .NET 4.8 |    8 |       1,607.4 ns |        40.11 ns |       115.08 ns |       1,600.0 ns |
|     New |   .NET 4.8 |    8 |         565.6 ns |        25.19 ns |        71.47 ns |         600.0 ns |
| Current | CoreRt 3.1 |    8 |         740.0 ns |        26.78 ns |        74.65 ns |         700.0 ns |
|     New | CoreRt 3.1 |    8 |         409.5 ns |        42.86 ns |       122.97 ns |         400.0 ns |
| Current |   .NET 4.8 |   16 |       6,247.4 ns |       124.98 ns |       138.92 ns |       6,300.0 ns |
|     New |   .NET 4.8 |   16 |       1,664.6 ns |        37.65 ns |        99.84 ns |       1,700.0 ns |
| Current | CoreRt 3.1 |   16 |       2,216.7 ns |        45.95 ns |        90.70 ns |       2,200.0 ns |
|     New | CoreRt 3.1 |   16 |       1,152.6 ns |        51.56 ns |       147.92 ns |       1,100.0 ns |
| Current |   .NET 4.8 |   32 |      18,814.3 ns |       145.79 ns |       129.24 ns |      18,800.0 ns |
|     New |   .NET 4.8 |   32 |       5,725.9 ns |       112.95 ns |       158.34 ns |       5,700.0 ns |
| Current | CoreRt 3.1 |   32 |       8,261.5 ns |       104.15 ns |        86.97 ns |       8,300.0 ns |
|     New | CoreRt 3.1 |   32 |       3,626.7 ns |        67.80 ns |       101.48 ns |       3,600.0 ns |
| Current |   .NET 4.8 |   64 |      79,161.5 ns |       562.84 ns |       470.00 ns |      79,100.0 ns |
|     New |   .NET 4.8 |   64 |      21,280.0 ns |       406.48 ns |       380.23 ns |      21,300.0 ns |
| Current | CoreRt 3.1 |   64 |      29,207.7 ns |       438.54 ns |       366.20 ns |      29,100.0 ns |
|     New | CoreRt 3.1 |   64 |      13,020.0 ns |       255.10 ns |       381.83 ns |      12,900.0 ns |
| Current |   .NET 4.8 |  128 |     326,438.5 ns |     2,859.31 ns |     2,387.66 ns |     326,700.0 ns |
|     New |   .NET 4.8 |  128 |      82,456.7 ns |     1,618.92 ns |     2,423.12 ns |      83,300.0 ns |
| Current | CoreRt 3.1 |  128 |     115,719.2 ns |       556.10 ns |       464.37 ns |     115,550.0 ns |
|     New | CoreRt 3.1 |  128 |      49,707.7 ns |       851.66 ns |       711.17 ns |      49,600.0 ns |
| Current |   .NET 4.8 |  256 |   1,260,860.0 ns |    13,735.23 ns |    12,847.95 ns |   1,256,100.0 ns |
|     New |   .NET 4.8 |  256 |     337,318.2 ns |     6,707.29 ns |    10,638.48 ns |     337,900.0 ns |
| Current | CoreRt 3.1 |  256 |     465,521.4 ns |     4,819.23 ns |     4,272.12 ns |     465,650.0 ns |
|     New | CoreRt 3.1 |  256 |     189,084.6 ns |       736.34 ns |       614.88 ns |     189,100.0 ns |
| Current |   .NET 4.8 |  512 |   5,292,871.4 ns |    43,246.91 ns |    38,337.26 ns |   5,294,200.0 ns |
|     New |   .NET 4.8 |  512 |   1,351,013.3 ns |    24,770.19 ns |    23,170.05 ns |   1,355,600.0 ns |
| Current | CoreRt 3.1 |  512 |   1,923,033.3 ns |    38,317.74 ns |    45,614.54 ns |   1,907,900.0 ns |
|     New | CoreRt 3.1 |  512 |     768,300.0 ns |     8,805.14 ns |     8,236.33 ns |     770,000.0 ns |
| Current |   .NET 4.8 | 1024 |  20,712,314.3 ns |   144,666.75 ns |   128,243.30 ns |  20,714,500.0 ns |
|     New |   .NET 4.8 | 1024 |   5,203,200.0 ns |   102,944.55 ns |   188,239.94 ns |   5,294,150.0 ns |
| Current | CoreRt 3.1 | 1024 |   7,803,133.3 ns |    98,370.99 ns |    92,016.28 ns |   7,785,400.0 ns |
|     New | CoreRt 3.1 | 1024 |   3,101,288.9 ns |    61,777.47 ns |    66,101.20 ns |   3,080,750.0 ns |
| Current |   .NET 4.8 | 2048 |  81,628,326.7 ns |   293,235.54 ns |   274,292.70 ns |  81,650,700.0 ns |
|     New |   .NET 4.8 | 2048 |  20,049,175.0 ns |   118,740.53 ns |    92,704.79 ns |  20,045,750.0 ns |
| Current | CoreRt 3.1 | 2048 |  30,131,207.7 ns |   125,104.01 ns |   104,467.51 ns |  30,115,900.0 ns |
|     New | CoreRt 3.1 | 2048 |  12,291,060.0 ns |   165,825.61 ns |   155,113.38 ns |  12,307,600.0 ns |
| Current |   .NET 4.8 | 4096 | 325,866,793.3 ns |   732,597.77 ns |   685,272.41 ns | 325,993,300.0 ns |
|     New |   .NET 4.8 | 4096 |  82,090,373.3 ns | 1,930,869.79 ns | 1,806,136.80 ns |  81,160,600.0 ns |
| Current | CoreRt 3.1 | 4096 | 121,594,757.1 ns |   246,554.96 ns |   218,564.55 ns | 121,579,500.0 ns |
|     New | CoreRt 3.1 | 4096 |  50,676,080.0 ns |   191,101.54 ns |   178,756.50 ns |  50,638,200.0 ns |

**Comment by ZacharyPatten** [comment]
This may help:

```cs
using System;
using System.Linq;
using Towel;
using Towel.DataStructures;
using static Towel.Syntax;

namespace ConsoleApp2
{
	class Program
	{
		static void Main()
		{
			// Helpers
			static CompareResult CompareStrings(string a, string b) => Compare.Wrap(a.CompareTo(b));
			static string ToEnglishWords(int a) => a.ToEnglishWords();

			int[] values = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, };
			Console.WriteLine("Unsorted Values:");
			{
				int i = 0;
				values.Stepper(x => Console.WriteLine("  " + i++ + ": " + values[x].ToEnglishWords()));
			}
			Console.WriteLine();
			{ // sorting an array
				string[] array = values.Select(ToEnglishWords).ToArray();
				Console.WriteLine("Array:");
				Sort.Bubble(array);
				Stepper.Iterate(values.Length, x => Console.WriteLine("  " + x + ":" + array[x]));
			}
			Console.WriteLine();
			{ // sorting an System.Collections.Generic.List<T>
				var list = values.Select(ToEnglishWords).ToList();
				Console.WriteLine("List:");
				Sort.Bubble(0, values.Length - 1, i => list[i], (i, v) => list[i] = v, CompareStrings);
				Stepper.Iterate(values.Length, x => Console.WriteLine("  " + x + ":" + list[x]));
			}
			Console.WriteLine();
			{ // sorting System.Collections.Generic.Dictionary<TKey, TValue>
				var dictionary = values.ToDictionary(x => x, ToEnglishWords);
				Sort.Bubble(0, values.Length - 1, i => dictionary[i], (i, v) => dictionary[i] = v, CompareStrings);
				Console.WriteLine("Dictionary:");
				Stepper.Iterate(values.Length, x => Console.WriteLine("  " + x + ":" + dictionary[x]));
			}
			Console.WriteLine();
			{ // sorting Towel.DataStructures.MapHashLinked<T, K>
				var map = new Towel.DataStructures.MapHashLinked<string, int>();
				Stepper.Iterate(values.Length, x => map.Add(x, x.ToEnglishWords()));
				Sort.Bubble(0, values.Length - 1, i => map[i], (i, v) => map[i] = v, CompareStrings);
				Console.WriteLine("Map:");
				Stepper.Iterate(values.Length, x => Console.WriteLine("  " + x + ":" + map[x]));
			}
			Console.WriteLine();
		}
	}
}
```

The `Memory<T>` type can only be used on the array type from above. It cannot allow you to pass in a `Dictionary<T>` into the code. But when you abstract the getters/setters (as I did in the code in Towel) you can allow the algorithm to be used with any data structure that is `int` indexed.

Is it slower than `Memory<T>`? Yes absolutely. But it prevents you from having to copy all the data from a data structure into a `Memory<T>`, sort it, and then dump it into a new data structure, which (in total) can save a lot more than time overall depending on the scenario.

The `Memory<T>` type is unfortunately not supported when abstracting the getters/setters due to the restrictions of being a `readonly struct`. Thus... The only course of action is to include two versions of the algorithms: one that abstracts the getters/setters and one that works on `Memory<T>`.

**Comment by HurricanKai** [comment]
I don't quite understand how sorting a HashMap or Dictionary makes sense, as they are order independent?
for the others, it's quite simple to adjust.
```cs
int[] values = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, };
Console.WriteLine("Unsorted Values:");
{
    int i = 0;
    values.Stepper(x => Console.WriteLine("  " + i++ + ": " + values[x].ToEnglishWords()));
}
Console.WriteLine();
{ // sorting an array
    string[] array = values.Select(ToEnglishWords).ToArray();
    Console.WriteLine("Array:");
    // Sort.Bubble(array);
    BubbleSort.New<string, Comparer<string>>(array, Comparer<string>.Default);
    Stepper.Iterate(values.Length, x => Console.WriteLine("  " + x + ":" + array[x]));
}
Console.WriteLine();
{ // sorting an System.Collections.Generic.List<T>
    var list = values.Select(ToEnglishWords).ToList();
    Console.WriteLine("List:");
    // Sort.Bubble(0, values.Length - 1, i => list[i], (i, v) => list[i] = v, CompareStrings);
    var arr = list.ToArray();
    BubbleSort.New<string, Comparer<string>>(arr, Comparer<string>.Default);
    list = arr.ToList();
    Stepper.Iterate(values.Length, x => Console.WriteLine("  " + x + ":" + list[x]));
}
Console.WriteLine();
```

For testing purposes, I always used this, to not be influenced by Array vs Memory speeds:
```cs
public struct GetIndexMemory<T> : IGetIndex<T>, IFunc<int, T>
{
    internal ReadOnlyMemory<T> Memory;

    /// <summary>The invocation of the compile time delegate.</summary>
    public T Do(int index)
    {
        return this.Memory.Span[index];
    }

    /// <summary>Implicitly gets the getter from memory.</summary>
    /// <param name="memory">The memory to get the getter of.</param>
    public static implicit operator GetIndexMemory<T>(ReadOnlyMemory<T> memory)
    {
        return new GetIndexMemory<T>() { Memory = memory };
    }
    
    /// <summary>Implicitly gets the getter from memory.</summary>
    /// <param name="memory">The memory to get the getter of.</param>
    public static implicit operator GetIndexMemory<T>(Memory<T> memory)
    {
        return new GetIndexMemory<T>() { Memory = memory };
    }
}

public struct SetIndexMemory<T> : ISetIndex<T>, IAction<int, T>
{
    internal Memory<T> Memory;

    /// <summary>The invocation of the compile time delegate.</summary>
    public void Do(int index, T value)
    {
        this.Memory.Span[index] = value;
    }

    /// <summary>Implicitly gets the setter from memory.</summary>
    /// <param name="memory">The memory to get the setter of.</param>
    public static implicit operator SetIndexMemory<T>(Memory<T> memory)
    {
        return new SetIndexMemory<T>() { Memory = memory };
    }
}
```

I do understand why you made the Get/Set abstractions, but I feel like it would be way easier and faster to just make a Span, using whatever logic hides behind get/set.

I would be possible to provide overloads using Get/Set that just initially copy the entire range to a Span (using Get) and after the algorithm, they Copy back (using Set). What do you think about that?

**Comment by ZacharyPatten** [comment]
I like your `Memory<T>` code :). That is exactly what I had in mind as well (I just hadn't had time to add it yet).

As for the `Dictuonary<K, T>` question, I don't see many users needing to use it on a `Dictionary<K, T>` specifically, but it was only an example to show that it could be used on pretty much anything. Here is another example where I sort a multidimensional array:

```cs
using System;
using Towel;
using static Towel.Syntax;
using System.Text;

class Program
{
	class Person
	{
		public int Id;
		public string FirstName;
		public string LastName;
		public DateTime DateOfBirth;
	}

	const int Rows = 3;
	const int Columns = 3;
	const int Count = Rows * Columns;
	static readonly Person[,] people = new Person[Rows, Columns];
	static readonly DateTime min = new DateTime(1950, 1, 1);
	static readonly DateTime max = new DateTime(2010, 1, 1);
	static readonly Random random = new Random();

	static void Main()
	{
		for (int row = 0, i = 0; row < Rows; row++)
		{
			for (int column = 0; column < Columns; column++, i++)
			{
				people[column, row] = new Person()
				{
					Id = i,
					FirstName = i.ToEnglishWords(),
					LastName = random.NextAlphabeticString(10),
					DateOfBirth = random.NextDateTime(min, max),
				};
			}
		}

		Console.WriteLine("Original Order:");
		WritePeopleBoard();

		Console.WriteLine("Sorted On First Name:");
		Sort.Bubble(0, Count - 1, FlattenGet(people), FlattenSet(people), (a, b) => Comparison(a.FirstName, b.FirstName));
		WritePeopleBoard();

		Console.WriteLine("Sorted On Last Name:");
		Sort.Bubble(0, Count - 1, FlattenGet(people), FlattenSet(people), (a, b) => Comparison(a.LastName, b.LastName));
		WritePeopleBoard();

		Console.WriteLine("Sorted On Date Of Birth:");
		Sort.Bubble(0, Count - 1, FlattenGet(people), FlattenSet(people), (a, b) => Comparison(a.DateOfBirth, b.DateOfBirth));
		WritePeopleBoard();
	}

	public static GetIndex<T> FlattenGet<T>(T[,] multiArray) => i => multiArray[i % Columns, i / Columns];
	public static SetIndex<T> FlattenSet<T>(T[,] multiArray) => (i, v) => multiArray[i % Columns, i / Columns] = v;

	static void WritePeopleBoard()
	{
		var stringBuilder = new StringBuilder();
		stringBuilder.AppendLine("{");
		for (int row = 0, i = 0; row < Rows; row++, i++)
		{
			stringBuilder.Append("  {  ");
			for (int column = 0; column < Columns; column++)
			{
				Person person = people[column, row];
				stringBuilder.Append("[");
				stringBuilder.Append(person.Id);
				stringBuilder.Append(", ");
				stringBuilder.Append(person.FirstName);
				stringBuilder.Append(", ");
				stringBuilder.Append(person.LastName);
				stringBuilder.Append(", ");
				stringBuilder.Append(person.DateOfBirth.ToString(@"MM/dd/yyyy"));
				stringBuilder.Append("]");
				stringBuilder.Append(", ");
			}
			stringBuilder.AppendLine("  },");
		}
		stringBuilder.AppendLine("}");
		Console.WriteLine(stringBuilder);
	}
}
```

Calling `ToArray()` creates a clone of the data on the memory heap.

What about permanent memory (forget about data structures)? The algorithms in Towel could also be used on data in files as opposed to RAM. Just provide a getter/setter that look up the values in permanent memory (files).

**Comment by ZacharyPatten** [comment]
For the question about converting data to a `Span<T>`/`Memory<T>` for the sort and then moving it back into the original data structure, I'm all for it, but IMO that should be under a different method name than `Sort`. Maybe **"SortAsSpan"** or something along those lines. To me, if I call "Sort" on a data structure, I want to to sort the data structure I give it (not re-allocate a new data structure), but "SortAsSpan" would be obvious it is not sorting the structure I give it.

**Comment by ZacharyPatten** [comment]
closing this as it is stale

**Pull request closed without merging**
