### PR TITLE
SkipList<T> feature

### PR DESCRIPTION
**Pull request by AzuxirenLeadGuy**
This PR contains changes to the following files:

- **Sources/Towel/DataStructures/SkipList.cs**: SkipList<T> supporting basic `Add()`, `Remove()` `Search()` operations as well as some others.
- **Tools/Towel_Testing/DataStructures/SkipList.cs**: SkipList<T> tests

- **Sources/Towel/DataStructures/BTree.cs**: BTree<T> now implements the `Clone()` method 
- **Tools/Towel_Testing/DataStructures/BTree.cs**: BTree<T> tests for the `Clone()` method

I believe the basic `SkipList<T>` operations are optimal, but there's a lot of processing and additional extension methods to add, so I'm keeping it as a draft PR.

Related Issue: #34

### CODE REVIEW

**Comment by AzuxirenLeadGuy** [comment]
Done: 
- Fixed a few bugs 
- Added more interface to SkipList 
- Added an extension method for creating a new instance
- Updated Tests
- Updated Readme

A bit of documentation is remaining and some naming conventions which I'm leaving on you @ZacharyPatten. Let me know if you want to add any more features to this

**Comment by AzuxirenLeadGuy** [comment]
For the method  `void RemoveAll<TPredicate>(TPredicate predicate)` in the interface `IList<T>`, Should it be modified to have return type `int`, which is the number of elements removed using this method? I believe this would be more helpful, but that would mean modifications would be required for all data structures implementing `IList<T>`. What do you say?

**Comment by ZacharyPatten** [comment]
Let me think about `RemoveAll` for a bit before we make that change. Here are my initial thoughts on the topic:

- that would add a slight bit of overhead, but probably negligible in most cases
- users can already get the count that is removed by counting it themselves in the predicate they pass in
- some people may want the actual items that were removed (not just the count of items). for that case should there be another method, `ExtractAll`?

I think I agree, it probably should be `int` rather than `void`, but I just want to think about it for a bit first.

**Comment by AzuxirenLeadGuy** [comment]
> some people may want the actual items that were removed (not just the count of items). for that case should there be another method, ExtractAll?

I think that it is a bit too specific of a method to implement. It makes more sense to leave it on the users to modify the predicate so that they can suit it to their needs (the data structure to store the removed elements, for example).

The `System.Collection.Generic.List<T>` also has a `RemoveAll()` method which uses a predicate to remove elements. It does return `int`. So it is reasonable for users to expect a similar functionality.

**Comment by ZacharyPatten** [comment]
One other area I would like to edit is the `Examples/DataStructures`: https://github.com/ZacharyPatten/Towel/blob/main/Examples/DataStructures/Program.cs. Just a small usage example demonstrating add, look-up/contains, and remove. But examples can be added in future PRs if we don't get to it in this one.

**Comment by ZacharyPatten** [comment]
Made some changes. I still want to review it a bit more before merging.

I haven't implemented a skiplist fully myself, but I was under the impression that the levels can be dynamic so that you don't have to provide it on construction of the skip list. If that is true, then making it dynamic seems like the way to go. But I need to study up on skiplists and confirm.

**Comment by AzuxirenLeadGuy** [comment]
The levels are indeed dynamic (assigned on random), but I have placed a maximum limit on the maximum level to be reached by a node.

Here is my reasoning on having a limit on the current implementation.
- The `Front` of the `SkipList<T>` is a blank node that does not contain any data, but only references to the next nodes. This is necessary since I have implemented a singly-linked list, and for the purpose of deletion, it is needed to have the previous node beforehand. Therefore, this `Front` node should be linked to the first nodes of any level `k`, and the size of the array of links of `First` should accommodate all possible `k`. So for this reason I have fixed the maximum level of a node. 
- I believe this maximum level should be adjusted for the number of items in the SkipList to give as close of optimum performance to a Binary Search Tree (I could be wrong in this), so I figured that it would be best to leave the number of levels on the user.
- The more the levels, the more internal links to maintain for each node. This might imply that a lot of space gets taken up by reference links on nodes with higher levels, but it's not too bad since a node having `k` levels has a probability of (0.5)^k. 

Possible fixes:
- Instead of having an Array of references in a Node, maintain a Linked List of references. This way, The `Front` will initially have 0 elements in the references, and for every inserted node in the Skiplist having a new level, the `Front.Links` will require insertions as well. A drawback is that the `Search()` operation will be slightly slower since access for links in the middle is not `O(1)` as it used to be, and the `Add()` and `Remove()` operations use `Search()` for their respective tasks, meaning they would be slightly slower as well.
- Implement the SkipList as a doubly-linked list and get rid of `Front`. This will mean twice as much space is taken up by references, but that should not be that big of an issue.
- The cheapest fix would be to assign a large enough default value for the maximum level of a SkipList<T>. We can even implement a function to increase the maximum level for a given SkipList instance.

Let me know what you think is the best.

**Pull request merged**
