### PR TITLE
Multiple replacing for strings

### PR DESCRIPTION
**Pull request by WhiteBlackGoose**
It's a feature proposal. Instead of
```cs
myString.Replace("run", "ran").Replace("swim", "swam").Replace("go", "went")
```

We would write

```cs
myString.Replace(("run", "ran"), ("swim", "swam"), ("go", "went"))
```

No more loops like that:
```cs
foreach (var rule in rules)
    myString = myString.Replace(rule.old, rule.new);
```

Instead, we could write
```cs
myString = myString.Replace(myRules.Select(c => (c.old, c.new)));
```

Or, if our array/IEnumerable perfectly matches the argument,
```cs
myString = myString.Replace(rules);
```

If you accept features, you may Squash and merge so that commits do not flood your master

### CODE REVIEW

**Comment by ZacharyPatten** [comment]
I like this idea of this feature. It would be a great addition to Towel, but I think we can improve it. Rather than using a `foreach` loop to loop through all the rules, we could do a single loop through all the `char`s of the input `string`, and pattern match ourselves while we are looping. The current implementation is resulting in multiple loops through the string and multiple string allocations in memory. For large strings and lots of rules, that inefficiency might add up.

**Comment by WhiteBlackGoose** [comment]
I see, agree, I will fix it soon

**Comment by WhiteBlackGoose** [comment]
Alright, now it doesn't allocate as much memory as would be needed for N strings. However, it will allocate memory for each char in patterns because I do it via `linked list`.

Here we replace "ow" with "8000000"

image

We should somehow avoid so many allocations for `Node`. Maybe there's other algorithm, I will think I guess.

**Comment by WhiteBlackGoose** [comment]
Requires more work though

**Comment by ZacharyPatten** [comment]
I think something like this is what we want:
https://gist.github.com/ZacharyPatten/80e9d05e0b0ce814c9fe4277d8056480

**Comment by ZacharyPatten** [comment]
well crap

there was a much easier method... StringBuilder has a Replace method...

**Pull request closed without merging**
